// Generated by the Supabase CLI / MCP (`generate_typescript_types`) for the
// `mouzika-studio` project. Regenerate after schema changes; do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      achievements: {
        Row: {
          code: string
          color: string | null
          description: string | null
          icon: string | null
          name: string
        }
        Insert: {
          code: string
          color?: string | null
          description?: string | null
          icon?: string | null
          name: string
        }
        Update: {
          code?: string
          color?: string | null
          description?: string | null
          icon?: string | null
          name?: string
        }
        Relationships: []
      }
      content_changes: {
        Row: {
          added: Json
          change_type: string
          confidence: number | null
          created_at: string
          id: string
          removed: Json
          resolved_at: string | null
          resolved_by: string | null
          source: string | null
          status: string
          title: string
        }
        Insert: {
          added?: Json
          change_type: string
          confidence?: number | null
          created_at?: string
          id?: string
          removed?: Json
          resolved_at?: string | null
          resolved_by?: string | null
          source?: string | null
          status?: string
          title: string
        }
        Update: {
          added?: Json
          change_type?: string
          confidence?: number | null
          created_at?: string
          id?: string
          removed?: Json
          resolved_at?: string | null
          resolved_by?: string | null
          source?: string | null
          status?: string
          title?: string
        }
        Relationships: []
      }
      content_sources: {
        Row: {
          cadence: string | null
          id: string
          kind: string
          last_run: string | null
          name: string
          ok: boolean
        }
        Insert: {
          cadence?: string | null
          id?: string
          kind: string
          last_run?: string | null
          name: string
          ok?: boolean
        }
        Update: {
          cadence?: string | null
          id?: string
          kind?: string
          last_run?: string | null
          name?: string
          ok?: boolean
        }
        Relationships: []
      }
      courses: {
        Row: {
          color: string | null
          created_at: string
          description: string | null
          icon: string | null
          id: string
          slug: string
          sort_order: number
          status: string
          title: string
        }
        Insert: {
          color?: string | null
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          slug: string
          sort_order?: number
          status?: string
          title: string
        }
        Update: {
          color?: string | null
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          slug?: string
          sort_order?: number
          status?: string
          title?: string
        }
        Relationships: []
      }
      kb_entries: {
        Row: {
          body: Json
          category: string
          id: string
          kb_version: number
          read_min: number
          source_url: string | null
          summary: string | null
          title: string
          updated_at: string
        }
        Insert: {
          body: Json
          category: string
          id?: string
          kb_version?: number
          read_min?: number
          source_url?: string | null
          summary?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          body?: Json
          category?: string
          id?: string
          kb_version?: number
          read_min?: number
          source_url?: string | null
          summary?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      kb_releases: {
        Row: {
          id: string
          released_at: string
          released_by: string | null
          summary: string | null
          version: string
        }
        Insert: {
          id?: string
          released_at?: string
          released_by?: string | null
          summary?: string | null
          version: string
        }
        Update: {
          id?: string
          released_at?: string
          released_by?: string | null
          summary?: string | null
          version?: string
        }
        Relationships: []
      }
      lesson_progress: {
        Row: {
          completed_at: string
          lesson_id: string
          score: number | null
          user_id: string
        }
        Insert: {
          completed_at?: string
          lesson_id: string
          score?: number | null
          user_id: string
        }
        Update: {
          completed_at?: string
          lesson_id?: string
          score?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lesson_progress_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
        ]
      }
      lessons: {
        Row: {
          body: Json | null
          created_at: string
          id: string
          kind: string
          module_id: string
          slug: string
          sort_order: number
          status: string
          title: string
          xp_reward: number
        }
        Insert: {
          body?: Json | null
          created_at?: string
          id?: string
          kind?: string
          module_id: string
          slug: string
          sort_order?: number
          status?: string
          title: string
          xp_reward?: number
        }
        Update: {
          body?: Json | null
          created_at?: string
          id?: string
          kind?: string
          module_id?: string
          slug?: string
          sort_order?: number
          status?: string
          title?: string
          xp_reward?: number
        }
        Relationships: [
          {
            foreignKeyName: "lessons_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
        ]
      }
      mix_submissions: {
        Row: {
          created_at: string
          id: string
          metrics: Json
          report: Json | null
          score: number | null
          track_id: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          metrics: Json
          report?: Json | null
          score?: number | null
          track_id?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          metrics?: Json
          report?: Json | null
          score?: number | null
          track_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mix_submissions_track_id_fkey"
            columns: ["track_id"]
            isOneToOne: false
            referencedRelation: "tracks"
            referencedColumns: ["id"]
          },
        ]
      }
      modules: {
        Row: {
          course_id: string
          id: string
          sort_order: number
          title: string
        }
        Insert: {
          course_id: string
          id?: string
          sort_order?: number
          title: string
        }
        Update: {
          course_id?: string
          id?: string
          sort_order?: number
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "modules_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          bio: string | null
          created_at: string
          display_name: string | null
          genre: string | null
          handle: string | null
          id: string
          last_active: string | null
          level_label: string | null
          onboarding: Json
          plan: string
          streak: number
          xp: number
        }
        Insert: {
          bio?: string | null
          created_at?: string
          display_name?: string | null
          genre?: string | null
          handle?: string | null
          id: string
          last_active?: string | null
          level_label?: string | null
          onboarding?: Json
          plan?: string
          streak?: number
          xp?: number
        }
        Update: {
          bio?: string | null
          created_at?: string
          display_name?: string | null
          genre?: string | null
          handle?: string | null
          id?: string
          last_active?: string | null
          level_label?: string | null
          onboarding?: Json
          plan?: string
          streak?: number
          xp?: number
        }
        Relationships: []
      }
      srs_items: {
        Row: {
          due_at: string
          ease: number
          interval_days: number
          lapses: number
          reps: number
          topic_id: string
          user_id: string
        }
        Insert: {
          due_at?: string
          ease?: number
          interval_days?: number
          lapses?: number
          reps?: number
          topic_id: string
          user_id: string
        }
        Update: {
          due_at?: string
          ease?: number
          interval_days?: number
          lapses?: number
          reps?: number
          topic_id?: string
          user_id?: string
        }
        Relationships: []
      }
      srs_reviews: {
        Row: {
          id: number
          quality: number
          reviewed_at: string
          topic_id: string
          user_id: string
        }
        Insert: {
          id?: never
          quality: number
          reviewed_at?: string
          topic_id: string
          user_id: string
        }
        Update: {
          id?: never
          quality?: number
          reviewed_at?: string
          topic_id?: string
          user_id?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          current_period_end: string | null
          interval: string | null
          plan: string
          status: string
          stripe_customer_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          current_period_end?: string | null
          interval?: string | null
          plan?: string
          status?: string
          stripe_customer_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          current_period_end?: string | null
          interval?: string | null
          plan?: string
          status?: string
          stripe_customer_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      track_likes: {
        Row: {
          track_id: string
          user_id: string
        }
        Insert: {
          track_id: string
          user_id: string
        }
        Update: {
          track_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "track_likes_track_id_fkey"
            columns: ["track_id"]
            isOneToOne: false
            referencedRelation: "tracks"
            referencedColumns: ["id"]
          },
        ]
      }
      tracks: {
        Row: {
          audio_path: string | null
          bpm: number | null
          created_at: string
          genre: string | null
          id: string
          plays: number
          title: string
          user_id: string
        }
        Insert: {
          audio_path?: string | null
          bpm?: number | null
          created_at?: string
          genre?: string | null
          id?: string
          plays?: number
          title: string
          user_id: string
        }
        Update: {
          audio_path?: string | null
          bpm?: number | null
          created_at?: string
          genre?: string | null
          id?: string
          plays?: number
          title?: string
          user_id?: string
        }
        Relationships: []
      }
      user_achievements: {
        Row: {
          code: string
          earned_at: string
          user_id: string
        }
        Insert: {
          code: string
          earned_at?: string
          user_id: string
        }
        Update: {
          code?: string
          earned_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_achievements_code_fkey"
            columns: ["code"]
            isOneToOne: false
            referencedRelation: "achievements"
            referencedColumns: ["code"]
          },
        ]
      }
      user_state: {
        Row: {
          state: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          state?: Json
          updated_at?: string
          user_id: string
        }
        Update: {
          state?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      xp_events: {
        Row: {
          amount: number
          created_at: string
          id: number
          reason: string | null
          user_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          id?: never
          reason?: string | null
          user_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          id?: never
          reason?: string | null
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
